services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy-local
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx/vhost.d:/etc/nginx/vhost.d
      - ./docker/nginx/html:/usr/share/nginx/html
    networks:
      - webnet

  web1:
    build:
      context: ./first-class
    container_name: first-web-local
    networks:
      - webnet
      - fast
    volumes:
      - ./first-class:/first-class
    command: >
      bash -c "rm -f tmp/pids/server.pid &&
               npm install &&
               service cron start &&
               bundle exec whenever --update-crontab &&
               bundle exec rails tailwindcss:build &&
               bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      TZ: Asia/Tokyo
      VIRTUAL_HOST: first.localhost
    expose:
      - "3000"
    stdin_open: true
    tty: true
    depends_on:
      - mysql1

  mysql1:
    image: mysql:8.0
    container_name: mysql1-local
    networks:
      - webnet
    volumes:
      - ./docker/mysql1/data:/var/lib/mysql
      - ./docker/mysql1/conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=5swB2ANBrs
      - MYSQL_DATABASE=first_db
      - MYSQL_USER=first_user
      - MYSQL_PASSWORD=HF7_AVgxL3
    ports:
      - "3316:3306"
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin1:
    image: phpmyadmin
    networks:
      - webnet
    environment:
      PMA_HOST: mysql1
    ports:
      - 18180:80

  web2:
    build:
      context: ./mikado-system
    container_name: mikado-web-local
    networks:
      - webnet
      - fast
    volumes:
      - ./mikado-system:/mikado-system
    command: >
      bash -c "rm -f tmp/pids/server.pid &&
               npm install &&
               service cron start &&
               bundle exec whenever --update-crontab &&
               bundle exec rails tailwindcss:build &&
               bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      TZ: Asia/Tokyo
      VIRTUAL_HOST: mikado.localhost
    expose:
      - "3000"
    stdin_open: true
    tty: true
    depends_on:
      - mysql2

  mysql2:
    image: mysql:8.0
    container_name: mysql2-local
    networks:
      - webnet
    volumes:
      - ./docker/mysql2/data:/var/lib/mysql
      - ./docker/mysql2/conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=5swB2ANBrs
      - MYSQL_DATABASE=mikado_db
      - MYSQL_USER=mikado_user
      - MYSQL_PASSWORD=HF7_AVgxL3
    ports:
      - "3326:3306"
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin2:
    image: phpmyadmin
    networks:
      - webnet
    environment:
      PMA_HOST: mysql2
    ports:
      - 18280:80

  fast-api:
    build:
      context: ./docker/fast-api
    volumes:
      - ./docker/fast-api/app:/app
      - ./docker/fast-api/requirements.txt:/app/requirements.txt
    networks:
      - fast
    ports:
      - 9000:9000

networks:
  webnet:
  fast: