services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      # /tmp/docker.sockじゃなくても使えるようにDocker環境変数を明示
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/nginx/certs:/etc/nginx/certs
      - ./docker/nginx/vhost.d:/etc/nginx/vhost.d
      - ./docker/nginx/html:/usr/share/nginx/html
    networks:
      - webnet

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=resaldev20240421@gmail.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/nginx/certs:/etc/nginx/certs
      - ./docker/nginx/vhost.d:/etc/nginx/vhost.d
      - ./docker/nginx/html:/usr/share/nginx/html
    depends_on:
      - proxy
    networks:
      - webnet

  web1:
    build:
      context: ./first-class
    networks:
      - webnet
    volumes:
      - ./first-class:/first-class
    command: bash -c "rm -f tmp/pids/server.pid && npm install && service cron start && bundle exec whenever --update-crontab && bundle exec rails tailwindcss:build && bundle exec wheneverize && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      TZ: Asia/Tokyo
      VIRTUAL_HOST: first.resal-dev.com
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: first.resal-dev.com
      LETSENCRYPT_EMAIL: resaldev20240421@gmail.com
    expose:
      - "3000"
    stdin_open: true
    tty: true
    depends_on:
      - mysql1

  mysql1:
    image: mysql:8.0
    networks:
      - webnet
    volumes:
      - ./docker/mysql1/data:/var/lib/mysql
      - ./docker/mysql1/custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=5swB2ANBrs
      - MYSQL_DATABASE=first_db
      - MYSQL_USER=first_user
      - MYSQL_PASSWORD=HF7_AVgxL3
    ports:
      - 3316:3306
    command: --default-authentication-plugin=mysql_native_password

  web2:
    build:
      context: ./mikado-system
    networks:
      - webnet
    volumes:
      - ./mikado-system:/mikado-system
    command: bash -c "rm -f tmp/pids/server.pid && npm install && service cron start && bundle exec whenever --update-crontab && bundle exec rails tailwindcss:build && bundle exec wheneverize && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      TZ: Asia/Tokyo
      VIRTUAL_HOST: mikado.resal-dev.com
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: mikado.resal-dev.com
      LETSENCRYPT_EMAIL: resaldev20240421@gmail.com
    expose:
      - "3000"
    stdin_open: true
    tty: true
    depends_on:
      - mysql2

  mysql2:
    image: mysql:8.0
    networks:
      - webnet
    volumes:
      - ./docker/mysql2/data:/var/lib/mysql
      - ./docker/mysql2/custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=5swB2ANBrs
      - MYSQL_DATABASE=mikado_db
      - MYSQL_USER=mikado_user
      - MYSQL_PASSWORD=HF7_AVgxL3
    ports:
      - 3326:3306
    command: --default-authentication-plugin=mysql_native_password

networks:
  webnet:
